### ISSUE TITLE
Issue with AJAX front end register call

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/express-group-project#19]
Running front end on localhost:5000

This is the error in the console on the web page.

```javascript

success
:3000/signup:1 POST http://localhost:3000/signup 500 (Internal Server Error)
ajax.js:27 Object {jqxher: Object, status: "error", error: "Internal Server Error"}
```

this is the jquery call 

```javascript 
$('#register').on('submit', function(e) {
        e.preventDefault();
        var credentials = wrap('credentials', form2object(this));
        packrat.register(credentials, callback);
      });```

and this is the AJAX call

```javascript

register: function (credentials, callback) {
    this.ajax({
      method: 'POST',
      url: this.url + '/signup',
      contentType: 'application/json',
      data: JSON.stringify(credentials),
      dataType: 'json'
    }, callback);
    console.log("success");
  },```

this is my server error on the backend:
POST /signup 500 9.229 ms - 2079

I looked up 500 errors but they are the errors that get thrown when they do not know the specific cause.

**Comment by jcmeyer10** [comment]
Success is the response I log when the POST goes through just for clarification.  I will gladly provide more information as needed.

**Comment by gaand** [comment]
What errors does express show in the terminal?

**Comment by jcmeyer10** [comment]
If I understand your question correctly, in the terminal running the backend server I get this error

POST /signup 500 120.732 ms - 2079

Is this the information you were looking for?

**Comment by gaand** [comment]
Is that the only error?  There should be a stack trace if the server sends a 500.

**Comment by jcmeyer10** [comment]
from NPM start to the request, that's all I get

```javascript

~/WDI/packrat/packRat-backend2 (development)$ npm start

> packRat-backend@0.0.0 start /Users/JeffMeyer/WDI/packrat/packRat-backend2
> node ./bin/www

POST /signup 500 120.732 ms - 2079```

**Comment by gaand** [comment]
Please try `DEBUG=packRat-backend2:* npm start` and see if you get more information.

**Comment by jcmeyer10** [comment]
```javascript ~/WDI/packrat/packRat-backend2 (development)$ DEBUG=packRat-backend2:* npm start

> packRat-backend@0.0.0 start /Users/JeffMeyer/WDI/packrat/packRat-backend2
> node ./bin/www

**Comment by jcmeyer10** [comment]
I get a 405 (method not allowed) error on my backend and when i try to access localhost3000/signup

**Comment by jcmeyer10** [comment]
We have CORS enable in our Express app in app.js 
```javascript
(var cors = require('cors')
//and slightly farther down
app.use(cors({
  origin: ['http://localhost:5000'],
  credentials: true
}));

**Comment by gaand** [comment]
Please post the code for the route and controller you're trying to invoke.

**Comment by jcmeyer10** [comment]
this is the route (from the express passport lesson
```javascript
var express = require('express');
var router = express.Router();
var authCtrl = require('../controllers/auth');

/* GET home page. */
router.get('/', authCtrl.root.get);

/**AUTH ROUTES
 *  a login route using `passport.authenticate`
 *  a register route **not using passport**
 *
 */
router.route('/login').
    get(authCtrl.deny).
    post(authCtrl.login.post).
    all(authCtrl.login.all);

router.route('/logout').
  all(authCtrl.logout.all);

router.route('/changePassword').
  get(authCtrl.deny).
  patch(authCtrl.changePassword.patch);

router.route('/signup').
  get(authCtrl.deny).
  post(authCtrl.signup.post);

module.exports = router;

**Comment by jcmeyer10** [comment]
this is the controller (again from passport lesson)

```javascript

'use strict';

var passport = require('passport');
var User = require('../models').model('User');
module.exports = {
    deny : function(req, res) {
            res.sendStatus(405);
    },
    root : {
        get : function(req, res) {
            res.json({
                title : (req.user && req.user.userName) || 'Nobody'
            });
        }
    },
    login : {
        post : passport.authenticate('local'),
        all : function(req, res) {
            res.sendStatus(200);
        }
    },
    logout : {
        all : function(req, res, next) {
            if(!req.user) {
                var err = new Error("Log in first.");
                return next(err);
            }

            req.logout();
            res.sendStatus(200);
        }
    },
    changePassword : {
        patch : function(req, res, next) {
            // check that user is logged in
            // check that body contains a password value
            if(!req.body || !req.user || !req.body.password) {
                var err = new Error("No password supplied.");
                return next(err);
            }
            // bcrypt the password
            req.user.setPassword(req.body.password).
                then(function() {
                    res.sendStatus(200);
                }).catch(function(err) {
                    next(err);
                });
        }
    },
    signup : {
        post : function(req, res, next) {
            if(!req.body || !req.body.username || !req.body.password) {
                var err = new Error("No credentials.");
                return next(err);
            }

            var pUser = new Promise(function(res, rej) {
                User.create({
                    userName : req.body.username
                }, function(err, user) {
                    if(err) {
                        rej(err);
                        return;
                    }

                    res(user);
                });
            });
            pUser.then(function(user) {
                return user.setPassword(req.body.password);
            }).then(function() {
                res.sendStatus(200);
            }).catch(function(err) {
                next(err);
            });
        }
    }
};

**Comment by gaand** [comment]
Did you get method not allowed when running the jQuery at the top of this issue?  Or was that trying to open the url in the browser?

**Comment by jcmeyer10** [comment]
Sorry, just didn't see this.  When I opened in the browser.  So theAuthCtrl is working because that is denied, and only POST is allowed.

**Comment by gaand** [comment]
Okay.  So, running express with debug, do you get more info with the 500 error?

**Comment by jcmeyer10** [comment]
by the grace of chtuhlu I do.  I swear it didn't do this before.

```javascript

~/WDI/packrat/packRat-backend2 (development)$ DEBUG=packRat-backend2:* npm start

> packRat-backend@0.0.0 start /Users/JeffMeyer/WDI/packrat/packRat-backend2
> node ./bin/www

/Users/JeffMeyer/WDI/packrat/packRat-backend2/routes/index.js:7
app.use(function(req, res, next) {
^

ReferenceError: app is not defined
    at Object.<anonymous> (/Users/JeffMeyer/WDI/packrat/packRat-backend2/routes/index.js:7:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/JeffMeyer/WDI/packrat/packRat-backend2/app.js:19:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/JeffMeyer/WDI/packrat/packRat-backend2/bin/www:8:11)
    at Module._compile (module.js:435:26)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/JeffMeyer/.nvm/versions/node/v4.2.2/bin/node" "/Users/JeffMeyer/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! packRat-backend@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the packRat-backend@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the packRat-backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls packRat-backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JeffMeyer/WDI/packrat/packRat-backend2/npm-debug.log
~/WDI/packrat/packRat-backend2 (development)$

**Comment by jcmeyer10** [comment]
this is the first line it refers to

```javascript

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

**Comment by jcmeyer10** [comment]
I put that in because I looked at the CORS documentation found here

http://enable-cors.org/server_expressjs.html

**Comment by jcmeyer10** [comment]
Put this line in the index.js routes file and got this error:

TypeError: app.use is not a function

```javascript
var app = require('../app.js');

**Comment by jcmeyer10** [comment]
When using nodemon, and I make a change, this reloading the server I get this 
```javascript
OPTIONS /signup 200 50.589 ms - 13

**Comment by jcmeyer10** [comment]
in the back end server terminal

**Comment by srhoulam** [comment]
The problem revolved around not sending a body in the requests made to the backend for logging in and signing up. Also manually setting CORS headers *after* using the CORS module.

**Comment by jcmeyer10** [comment]
The server was expecting a username and password and by keeping the wrap('credentials') it was wrapping it up in an object. I was also specifying for dataType: JSON when text would be more appropriate but nothing would be the best solution.

Also the forms needed a name so the call jQuery was pulling data from matching labels.
