### ISSUE TITLE
running into this error secret option required for sessions

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/express-group-project#3]
when I try to access localhost:3000 I get this in the server log
```javascript
express-session deprecated req.secret; provide secret option app.js:35:9```

and this in the browser
```javascript 

secret option required for sessions

Error: secret option required for sessions
    at session (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express-session/index.js:167:12)
    at Layer.handle [as handle_request] (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/lib/router/index.js:312:13)
    at /Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/node_modules/send/index.js:245:17)
    at SendStream.onStatError (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/node_modules/send/index.js:356:12)
    at next (/Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/node_modules/send/index.js:658:28)
    at /Users/JeffMeyer/.Trash/packRat/packRat-backend/node_modules/express/node_modules/send/index.js:666:23
    at FSReqWrap.oncomplete (fs.js:82:15) ```

**Comment by jcmeyer10** [comment]
I have tried to go back to express-passport lesson, and trying to figure out answer online through the normal methods.

**Comment by srhoulam** [comment]
Jeff, this error message is very pointedly complaining that your session middleware is missing a secret. Can you post the options object you pass to the express-session module here?

**Comment by jcmeyer10** [comment]
This is what my app.js looks like ```javascript 
app.use(cookieParser('secret'));
app.use(cookieSession());
app.use(express.static(path.join(__dirname, 'public')));

app.use(session({
  secret : process.env.SESSION_SECRET,
  resave : false,
  saveUninitialized : false,
  store : new MongoStore({
    url : "mongodb://localhost/ga-passport-sessions"
  }),
  cookie : {
    maxAge : 300000 // 5 minutes
  },
  genid : function() {
    return uuid.v4({
      rng : uuid.nodeRNG
    });
  }
}));```

**Comment by srhoulam** [comment]
Do you have a `.env` file that sets a `SESSION_SECRET` environment variable?

**Comment by jcmeyer10** [comment]
in my .env file I have a access key id, secret access key and aws_bucket

**Comment by srhoulam** [comment]
I'll come help you generate a session secret.

**Comment by srhoulam** [comment]
Generating a session secret:

```
var secret;

require('crypto').randomBytes(16, function(err, bytes) {
    secret = bytes.toString('base64');
});
```

You can run this in node REPL and copy and paste the contents of `secret` when it becomes non-empty.
