### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/express-group-project#33]
Our server is not connecting anymore and give this error. It happened when we realized the delete controller was changed to use .exec(). Not sure how to read this to make sense of it. 

```nodemon] starting `node ./bin/www`
/Users/lgrant1286/WDI/Project3/project3-back-end/node_modules/express/lib/router/route.js:196
        throw new Error(msg);
        ^

Error: Route.delete() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as delete] (/Users/lgrant1286/WDI/Project3/project3-back-end/node_modules/express/lib/router/route.js:196:15)
    at Function.proto.(anonymous function) [as delete] (/Users/lgrant1286/WDI/Project3/project3-back-end/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/lgrant1286/WDI/Project3/project3-back-end/routes/post.js:16:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/lgrant1286/WDI/Project3/project3-back-end/app.js:18:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gaand** [comment]
Please post the router and controller code.

**Comment by LaurenGrant** [comment]
We have reset to an earlier commit right now to get the db working again and right now it is. I will open this issue back up if the problem comes back.
