### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/express-group-project#35]
Currently getting the following heroku log errors:

```
2015-12-02T00:20:50.890675+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-02T00:20:50.903402+00:00 app[web.1]: 
2015-12-02T00:20:50.908747+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-02T00:20:50.909049+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-02T00:20:50.909719+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-12-02T00:20:50.909985+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-02T00:20:50.910140+00:00 app[web.1]: npm ERR! node-express-session@0.0.0 start: `node ./bin/www`
2015-12-02T00:20:50.910249+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-02T00:20:50.910387+00:00 app[web.1]: npm ERR! 
2015-12-02T00:20:50.910563+00:00 app[web.1]: npm ERR! Failed at the node-express-session@0.0.0 start script 'node ./bin/www'.
2015-12-02T00:20:50.910735+00:00 app[web.1]: npm ERR! This is most likely a problem with the node-express-session package,
2015-12-02T00:20:50.910893+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-02T00:20:50.911048+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-02T00:20:50.911207+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-02T00:20:50.911362+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-02T00:20:50.911517+00:00 app[web.1]: npm ERR!     npm owner ls node-express-session
2015-12-02T00:20:50.911688+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-02T00:20:50.915040+00:00 app[web.1]: 
2015-12-02T00:20:50.915291+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-02T00:20:50.915474+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-02T00:20:51.783818+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-02T00:20:51.758327+00:00 heroku[web.1]: Process exited with status 1
2015-12-02T00:20:53.243386+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/polls" host=hidden-springs-2370.herokuapp.com request_id=b3db2a17-2b06-4f40-9a3e-2d2250635e68 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:20:53.491738+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hidden-springs-2370.herokuapp.com request_id=0e4dde9a-5a02-4a93-937d-cbd71dc91397 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:20:53.646467+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hidden-springs-2370.herokuapp.com request_id=e4388dfc-bea7-466b-80bd-9d3a9f1bac62 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:20:59.527492+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/users" host=hidden-springs-2370.herokuapp.com request_id=fa1c807d-e3ca-42b0-8f97-b00f353e86ba fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:20:59.843559+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hidden-springs-2370.herokuapp.com request_id=b298e37b-fa0d-42e1-bf33-8957de8954e1 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:27:47.355972+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-02T00:27:48.742637+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-02T00:27:51.553515+00:00 app[web.1]: 
2015-12-02T00:27:51.553524+00:00 app[web.1]: > node-express-session@0.0.0 start /app
2015-12-02T00:27:51.553526+00:00 app[web.1]: > node ./bin/www
2015-12-02T00:27:51.553527+00:00 app[web.1]: 
2015-12-02T00:27:52.528902+00:00 app[web.1]: 
2015-12-02T00:27:52.528907+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-02T00:27:52.528906+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-02T00:27:52.528908+00:00 app[web.1]:                                       ^
2015-12-02T00:27:52.528912+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-02T00:27:52.528912+00:00 app[web.1]:     at Object.exports._errnoException (util.js:860:11)
2015-12-02T00:27:52.528914+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-02T00:27:52.528913+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:883:20)
2015-12-02T00:27:52.559376+00:00 app[web.1]: 
2015-12-02T00:27:52.576367+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-02T00:27:52.576551+00:00 app[web.1]: npm ERR! node-express-session@0.0.0 start: `node ./bin/www`
2015-12-02T00:27:52.576702+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-02T00:27:52.576927+00:00 app[web.1]: npm ERR! 
2015-12-02T00:27:52.577130+00:00 app[web.1]: npm ERR! Failed at the node-express-session@0.0.0 start script 'node ./bin/www'.
2015-12-02T00:27:52.577347+00:00 app[web.1]: npm ERR! This is most likely a problem with the node-express-session package,
2015-12-02T00:27:52.577547+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-02T00:27:52.574766+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-02T00:27:52.577728+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-02T00:27:52.578193+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-02T00:27:52.574343+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-12-02T00:27:52.575050+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-02T00:27:52.578590+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-02T00:27:52.577955+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-02T00:27:52.578391+00:00 app[web.1]: npm ERR!     npm owner ls node-express-session
2015-12-02T00:27:52.582188+00:00 app[web.1]: 
2015-12-02T00:27:52.583343+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-02T00:27:52.575697+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-12-02T00:27:52.582433+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-02T00:27:53.469585+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-02T00:27:53.450761+00:00 heroku[web.1]: Process exited with status 1
2015-12-02T00:27:55.622314+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-02T00:27:56.591608+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-02T00:27:58.938576+00:00 app[web.1]: 
2015-12-02T00:27:58.938588+00:00 app[web.1]: > node-express-session@0.0.0 start /app
2015-12-02T00:27:58.938590+00:00 app[web.1]: > node ./bin/www
2015-12-02T00:27:58.938590+00:00 app[web.1]: 
2015-12-02T00:27:59.667686+00:00 app[web.1]: 
2015-12-02T00:27:59.667691+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-02T00:27:59.667692+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-02T00:27:59.667693+00:00 app[web.1]:                                       ^
2015-12-02T00:27:59.682831+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-12-02T00:27:59.684538+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-02T00:27:59.667739+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-02T00:27:59.667741+00:00 app[web.1]:     at Object.exports._errnoException (util.js:860:11)
2015-12-02T00:27:59.683119+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-02T00:27:59.684303+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-12-02T00:27:59.684865+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-02T00:27:59.683291+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-02T00:27:59.684715+00:00 app[web.1]: npm ERR! node-express-session@0.0.0 start: `node ./bin/www`
2015-12-02T00:27:59.667741+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:883:20)
2015-12-02T00:27:59.667743+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-02T00:27:59.678302+00:00 app[web.1]: 
2015-12-02T00:27:59.685035+00:00 app[web.1]: npm ERR! 
2015-12-02T00:27:59.685192+00:00 app[web.1]: npm ERR! Failed at the node-express-session@0.0.0 start script 'node ./bin/www'.
2015-12-02T00:27:59.685511+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-02T00:27:59.685668+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-02T00:27:59.685353+00:00 app[web.1]: npm ERR! This is most likely a problem with the node-express-session package,
2015-12-02T00:27:59.685970+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-02T00:27:59.686117+00:00 app[web.1]: npm ERR!     npm owner ls node-express-session
2015-12-02T00:27:59.685824+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-02T00:27:59.686264+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-02T00:27:59.689100+00:00 app[web.1]: 
2015-12-02T00:27:59.689323+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-02T00:27:59.689467+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-02T00:28:00.507806+00:00 heroku[web.1]: Process exited with status 1
2015-12-02T00:28:01.682129+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hidden-springs-2370.herokuapp.com request_id=6e38501c-bf13-4e20-b184-845db43236ef fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
2015-12-02T00:28:00.521216+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-02T00:28:02.129067+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hidden-springs-2370.herokuapp.com request_id=a1c45943-8179-469d-9965-d4e54278d4d1 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
```

A key has been added browser side on heroku and I have added node v4.2.2 and npm v3.4.1 to package.json engine. The errors above aren't super obvious to me as what to do next.

**Comment by MattB-GA-Boston** [comment]
Is it running locally?

**Comment by baz1389** [comment]
after running npm start:

```
> node-express-session@0.0.0 start /Users/benjaminspencer/WDI/surveyProject/survey-back-end
> node ./bin/www

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/connection.js:226:15)
    at Mongoose.connect (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/index.js:229:15)
    at Object.<anonymous> (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/models/index.js:8:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/lib/passport.js:9:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/benjaminspencer/.nvm/versions/node/v4.2.2/bin/node" "/Users/benjaminspencer/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE
npm ERR! node-express-session@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-express-session@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-express-session package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-express-session
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benjaminspencer/WDI/surveyProject/survey-back-end/npm-debug.log
```

**Comment by gaand** [comment]
The second error may be because you're calling `mongoose.connect` multiple times.

The first error is because you need to set up mongdb for heroku.

**Comment by baz1389** [comment]
I think we generally have an underlying mongoose.connect problem. We can get nodemon running now, but when I am trying to test CRUD out on the BE, our db.once() throws the following errors:

```
db.once('open', function() {
   ^

TypeError: db.once is not a function
    at Object.<anonymous> (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/scripts/tests.js:47:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
~/WDI/surveyProject/survey-back-end (bas-BECRUD)$ node scripts/tests.js u "565dea8330f8f14c3209e7cf" "title" "did it work?"
/Users/benjaminspencer/WDI/surveyProject/survey-back-end/scripts/tests.js:50
db.once('open', function() {
   ^

TypeError: db.once is not a function
    at Object.<anonymous> (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/scripts/tests.js:50:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

**Comment by gaand** [comment]
Please post the code the defines and assigns `db`.

**Comment by baz1389** [comment]
In app.js:

```
var db = require('./models/index.js');
```

models/index.js:

```
'use strict';

var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.model('User', require('./User'));
mongoose.model('Poll', require('./poll'));
mongoose.model('pollAnswer', require('./pollAnswer'));

mongoose.connect("mongodb://localhost/survey");

module.exports = mongoose;
```

**Comment by baz1389** [comment]
I think our issue is that we don't have a mongoose.connection and just need to declare var db = mongoose connection whereever we may be using it.

**Comment by gaand** [comment]
A few things:
Don't use db.once in the express app (it's fine in command line scripts).
The semantics of `db` as I presented them are `db = mongoose.connection`;

I don't understand what this code is for:
```
mongoose.model('User', require('./User'));
mongoose.model('Poll', require('./poll'));
mongoose.model('pollAnswer', require('./pollAnswer'));
```

**Comment by baz1389** [comment]
We are just using db.once for the test scripts. Does that mean we have retest CRUD on the backend?

**Comment by baz1389** [comment]
Oops, I think I misread your reply in regards to it being ok for testing purposes.

As for the mongoose.model portion, The User part was already in the index.js file when we cloned the repo, so I figured it might be worthwhile putting the other models in. I guess it's not though.

**Comment by gaand** [comment]
I think you want the model modules to export the created model, e.g.

```js
'use strict';

var mongoose = require('mongoose');

var myModelSchema = new mongoose.Schema({
...
});

var MyModel = mongoose.model('MyModel', myModelSchema);

module.exports = MyModel;
```

so that when you need a model you 
```js
var MyModel = require('../models/my-model.js');
```

**Comment by baz1389** [comment]
Yes, we have that. I think our confusion lies in the fact that 
```mongoose.model('User', require('./User'));
```
was required in our models/index.js file to begin with when we first cloned the express-passport repo.

**Comment by gaand** [comment]
That's interesting.  If the model modules are exporting the registered model, I'm not sure what those lines do (since the second argument is a schema, not a model)..

**Comment by LaurisaNeuwirth** [comment]
Antony, since we are a little confused about where/if all of our requires are right, could you come over and just review them with us quickly please?

**Comment by gaand** [comment]
I'll swing by after lunch.

**Comment by srhoulam** [comment]
They inherited that from my starter code. The model files export schemas, and models/index registers them with mongoose. They later use `mongoose.model` as a getter to get the needed model in their controller(s).

**Comment by jrhorn424** [comment]
Is this resolved?

**Comment by baz1389** [comment]
For now, yes.

**Comment by jrhorn424** [comment]
Thanks, @baz1389.
