### ISSUE TITLE
GET request with aggregation

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/express-group-project#48]
To preface:

```
var pollSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true
  },
  options: {
    type: []
  },
  owner_id: {
    type: String,
    required: true
  }
});
```

```
var pollAnswerSchema = new mongoose.Schema({
  pollID: {
    type: String,
    required: true
  },
  answer: {
    type: String,
    required: true
  }
});
```

We are trying to search a single Poll using the pollID key in the pollAnswer schema and then aggregate the answers that are already in the database. Below is the current code we have been trying out:

```
var read = function (req, res, next) {
  console.log("pollAnswer read params id is = ", req.params.id);
  pollAnswer.find({"pollID": req.body.pollAnswer}).exec()
  .then(function(){
    console.log("req query id: " + req.body.pollAnswer);
    var agg = pollAnswer.aggregate({ $match: {"pollID": "565f0a753cc192af11e897ba"}}, { $group: { "_id": "$answer", "count": { $sum: 1 } } });
    res.json(agg);
    console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};
```

curl http://localhost:3000/pollanswers/565f0a753cc192af11e897ba
```

server error:

```
pollAnswer read params id is =  565f0a753cc192af11e897ba
req query id: undefined
aggregation is: [object Object]
GET /pollanswers/565f0a753cc192af11e897ba 200 2.222 ms - 112
```

**Comment by srhoulam** [comment]
Line 3 inside your read function. `req.body.pollAnswer` looks like it should be `req.params.pollAnswer`.

**Comment by baz1389** [comment]
It is still sending the same errors when we tried req.params.pollAnswer and req.params.id

**Comment by srhoulam** [comment]
I need to see your routes to make any sense of this.

**Comment by baz1389** [comment]
pollAnswer:

```
var express = require('express');
var router = express.Router();
var pollCtrl = require('../controllers/poll.js');
var pollAnswerCtrl = require('../controllers/pollAnswer.js');

router.get('/', pollCtrl.index);

router.post('/', pollAnswerCtrl.create);

router.get('/:id', pollAnswerCtrl.read);

module.exports = router;
```

Polls:

```
'use strict'

var express = require('express');
var router = express.Router();
var pollCtrl = require('../controllers/poll.js');

router.get('/', pollCtrl.index);

router.post('/', pollCtrl.create);

router.get('/:id', pollCtrl.read);

router.put('/:id', pollCtrl.update);

router.delete('/:id', pollCtrl.destroy);

module.exports = router;

```

**Comment by srhoulam** [comment]
You want `req.params.id`, then.

**Comment by srhoulam** [comment]
```
var read = function (req, res, next) {
  console.log("pollAnswer read params id is = ", req.params.id);
  pollAnswer.find({"pollID": req.params.id}).exec()
  .then(function(/* retrieved documents will be passed to this function. it needs to take a parameter */){
    console.log("req query id: " + req.body.pollAnswer); // ?
    var agg = pollAnswer.aggregate({ $match: {"pollID": "565f0a753cc192af11e897ba"}}, { $group: { "_id": "$answer", "count": { $sum: 1 } } });
    res.json(agg);
    console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done); // what is `done`?
};
```

**Comment by baz1389** [comment]
done is a function that closes the database connection

```
var done = function() {
  db.close();
};
```

**Comment by baz1389** [comment]
Also req.params.id still didn't work

**Comment by srhoulam** [comment]
Remove that function and all references to it. Servers don't close their database connections.

**Comment by srhoulam** [comment]
(`done`)

**Comment by baz1389** [comment]
so we don't need another .then after catch?

**Comment by baz1389** [comment]
That didn't change anything either.

**Comment by srhoulam** [comment]
Are you using nodemon or restarting your back-end after making changes?

**Comment by baz1389** [comment]
nodemon

**Comment by srhoulam** [comment]
Have you seen the comments I added to your `read` function in a previous reply?

**Comment by srhoulam** [comment]
More specifically, is the function you pass to `then` the first time now taking a parameter?

**Comment by baz1389** [comment]
It is not.

**Comment by srhoulam** [comment]
Make it take one and have it log that parameter so you can see what is being passed in.

**Comment by baz1389** [comment]
Nothing is getting passed in.

**Comment by srhoulam** [comment]
That means no poll answers are being found with a `pollId` attribute that you specified.

**Comment by baz1389** [comment]
Just tried this:

```
var read = function (req, res, next) {
  console.log("pollAnswer read params id is = ", req.params.id);
  pollAnswer.find({"pollID": req.params.id}).exec()
  .then(function(poll){
    console.log("poll is: " + poll);
    console.log("req query id: " + req.body.pollAnswer);
    var agg = poll.findOne({"pollAnswer.pollID": "565f0a753cc192af11e897ba"});
    res.json(agg);
    console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};

```


Errors:

```
~/WDI/surveyProject/survey-back-end (bas-BECRUD)$ curl http://localhost:3000/pollanswers/565f0a753cc192af11e897ba
{"message":"poll.findOne is not a function","error":"TypeError: poll.findOne is not a function\n    at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/controllers/pollAnswer.js:29:20\n    at process._tickCallback (node.js:368:9)"}~/WDI/surveyProject/survey-back-end
```

**Comment by baz1389** [comment]
Update:

```
var read = function (req, res, next) {
  console.log("pollAnswer read params id is = ", req.params.id);
  pollAnswer.find({"pollID": req.params.id}).exec()
  .then(function(poll){
    console.log("poll is: " + poll);
    var agg = req.query.poll;
    console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};
```


server error:

```
pollAnswer read params id is =  565f0a753cc192af11e897ba
poll is: { __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f10fd91c9d2c713b545d3 },{ __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f1151845ef60214919c6b },{ __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f11640da5d20e14b1aa54 },{ __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b6bc9a37d41518b323 },{ __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b83b3630d815815aa2 },{ __v: 0,
  answer: 'fries',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f5bf5df8e3e6836cc63cb }
aggregation is: undefined
```

**Comment by jrhorn424** [comment]
`agg` is undefined because, at least in the example code you posted, `req.query.poll` is undefined.

In order for `req.query.poll` to have a value, you need to have a URL that ends with something like `?poll=somePollID`.

**Comment by baz1389** [comment]
We are currently trying to work with the following code and a hardcoded cURL command:

```
var read = function (req, res, next) {
  pollAnswer.find({"pollID": req.params.id}).exec()
  .then(function(polls){
    console.log("polls are: " + polls);
    console.log("pollAnswer read params id is = ", req.params.id);
    var agg = polls.forEach(function(pollAnswer){
      console.log("pollAnswer is: " + pollAnswer);
      var answer = req.body.pollAnswer;
      console.log("ANSWER is: " + answer);
      var choiceCount = {};
      if(!choiceCount.pollAnswer) {
        choiceCount.pollAnswer = 1;
        console.log("in if choice:" + choiceCount);
      } else {
        choiceCount.pollAnswer += 1;
        console.log("in else choice:" + choiceCount);
      }
    });
    console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};
```


CURL


```
curl http://localhost:3000/pollanswers/565f0a753cc192af11e897ba
```

**Comment by jrhorn424** [comment]
If you want your URLs to be like `/pollanswers/565f0a753cc192af11e897ba`, then inside your function you should use `req.params.pollId` with a route endpoint defined as `/pollanswers/:pollId`.

**Comment by LaurisaNeuwirth** [comment]
and you can see in there we recently created an object to hold the key:values of answer and the number of votes that answer got. We iterate through the pollAnswers to increment votes for each answer.

**Comment by jrhorn424** [comment]
Your thrashing. Pick a strategy: use query params with urls like `?poll=somePollId` or use dynamic routes with urls like `/pollanswers/somePollId`. The first requires you to grab the id with `req.query.poll`, the second with `req.params.pollId`, but only if your route is defined at `/pollanswers/:pollId`.

I need to see your route registration, not just the handler function.

**Comment by jrhorn424** [comment]
I might be missing something, but I'm definitely trying to answer the question of `aggregation is: undefined` with all my previous comments.

**Comment by LaurisaNeuwirth** [comment]
I was telling you that just to let you know how we have been working on solving it ourselves too.

**Comment by jrhorn424** [comment]
Can you confirm you get no output from curl with your last code?

**Comment by jrhorn424** [comment]
@LaurisaNeuwirth I have no doubt.

**Comment by baz1389** [comment]
CURL:

```
curl http://localhost:3000/pollanswers/565f0a753cc192af11e897ba
```


Sever Response:

```
polls are: { __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f10fd91c9d2c713b545d3 },{ __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f1151845ef60214919c6b },{ __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f11640da5d20e14b1aa54 },{ __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b6bc9a37d41518b323 },{ __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b83b3630d815815aa2 },{ __v: 0,
  answer: 'fries',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f5bf5df8e3e6836cc63cb }
pollAnswer read params id is =  565f0a753cc192af11e897ba
pollAnswer is: { __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f10fd91c9d2c713b545d3 }
ANSWER is: undefined
in if choice:[object Object]
pollAnswer is: { __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f1151845ef60214919c6b }
ANSWER is: undefined
in if choice:[object Object]
pollAnswer is: { __v: 0,
  answer: 'salad',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f11640da5d20e14b1aa54 }
ANSWER is: undefined
in if choice:[object Object]
pollAnswer is: { __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b6bc9a37d41518b323 }
ANSWER is: undefined
in if choice:[object Object]
pollAnswer is: { __v: 0,
  answer: 'hamburger',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f12b83b3630d815815aa2 }
ANSWER is: undefined
in if choice:[object Object]
pollAnswer is: { __v: 0,
  answer: 'fries',
  pollID: '565f0a753cc192af11e897ba',
  _id: 565f5bf5df8e3e6836cc63cb }
ANSWER is: undefined
in if choice:[object Object]
aggregation is: undefined
```

**Comment by jrhorn424** [comment]
Is there a reason you aren't using the built-in Aggregate function? https://gist.github.com/kdelemme/9659364

**Comment by baz1389** [comment]
Yes, because I didn't know it existed.

**Comment by jrhorn424** [comment]
Noted.

**Comment by jrhorn424** [comment]
@baz1389 Will you ping me if you're still working on this in an hour? I'm not sure I'll be able to help much more (I haven't had a *ton* of practice with Mongo or Mongoose), but I want to follow up anyway. I'm going to head out.

**Comment by baz1389** [comment]
@jrhorn424 Will do. As always, thank you for the help!

**Comment by LaurisaNeuwirth** [comment]
TY @jrhorn424

**Comment by baz1389** [comment]
New pollAnswer route:

```
router.get('/:pollID', pollAnswerCtrl.read);
```


current read function:

```
var read = function (req, res, next) {
  pollAnswer.find({"pollID": req.params.pollID}).exec()
  .then(function(pollAnswers){
    console.log("pollAnswer read params id is = ", req.params.pollID);
    var agg = pollAnswers.forEach(function(pollAnswer){
      console.log("pollAnswer is: " + pollAnswer);
      var choiceCount = {};
      // if(!choiceCount.pollAnswer) {
      //   choiceCount.pollAnswer = 1;
      //   // console.log("in if choice:" + choiceCount);
      // } else {
      //   choiceCount.pollAnswer += 1;
      //   // console.log("in else choice:" + choiceCount);
      // }
    });
    // console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};
```

cURL command:

```
curl http://localhost:3000/pollanswers/565f0a753cc192af11e897ba
```

req.params.pollID gives us the pollID at the end of the URL provided in the above curl command. So the next thing I think we need to do is  use req.params.pollID in the forEach function and sum up all the answers.

**Comment by baz1389** [comment]
@gaand Would you have any available time to come look at this sometime soon?

**Comment by jrhorn424** [comment]
Please update this with the next non-JS (syntax, undefined, etc) error that you've tried to fix.

**Comment by baz1389** [comment]
In our controller file:

```
var db = require('../models/index.js');
var util = require('util');
var pollAnswer = require('../models/pollAnswer');
// var Poll = require('../models/poll');

var done = function() {
  db.close();
};

// var read = function (req, res, next) {
//   console.log("pollAnswer read params id is = ", req.params.id);
//   pollAnswer.find({"_id": req.body.id}).exec()
//   .then(function(pollAnswer){
//     var agg = pollAnswer.aggregate({ $match: {"pollID": "565f0a753cc192af11e897ba"}}, { $group: { "_id": "$answer", "count": { $sum: 1 } } });
//     res.json(agg);
//     console.log("aggregation is: " + agg);
//   }).catch(function(error){
//     next(error);
//   }).then(done);
// };

var read = function (req, res, next) {
  var pollID = req.params.pollID;
  console.log("HERE IS THE pollID " +pollID);
  pollAnswer.find({"pollID": req.params.pollID}).exec()
  .then(function(pollAnswer){
    console.log("pollAnswer read params id is = ", req.params.pollID);
    var agg = pollAnswer.aggregate([{ $match: {"pollID": "565f0a753cc192af11e897ba"}}, { $group: { "_id": "$answer", "count": { $sum: 1 } } }], function (err, result) {
        if (err) {
            console.log(err);
            return;
        }
        console.log(result);
    });
    // console.log("aggregation is: " + agg);
  }).catch(function(error){
    next(error);
  }).then(done);
};
```

Error being returned:

```
{"message":"pollAnswer.aggregate is not a function","error":"TypeError: pollAnswer.aggregate is not a function\n    at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/controllers/pollAnswer.js:30:26\n    at process._tickCallback (node.js:368:9)"}~/WDI/surveyProject/survey-back-end (bas-BECRUD)$ 
```


We've read the documentation and tried many iterations and are still blocked.

**Comment by gaand** [comment]
`aggregate` is a method on a model, not a document or document collection.  See http://mongoosejs.com/docs/api.html#model_Model.aggregate and https://docs.mongodb.org/v3.0/reference/operator/aggregation-pipeline/.  I believe you'll want to start with `$match`.

**Comment by baz1389** [comment]
Got it working:

```
var read = function (req, res, next) {
  pollAnswer.aggregate([{ $match: {"pollID": req.params.pollID}}, { $group: { "_id": "$answer", "count": { $sum: 1 } } }]
    ).exec().then(function(pollAnswer) {
    res.json(pollAnswer);
  }).catch(console.error).then(done);
};
```

**Comment by gaand** [comment]
Awesome!

BTW, we should talk about using `done`.  I'll come see you and then you can close this issue.
