### ISSUE TITLE
Single blog article route returning 404s for any methods

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/express-group-project#54]
After testing and tweaking my code for a little while and testing several different scenarios. I can't seem to find what is causing this strange error. The code that searches for a single article by `_id` at the route `localhost:3000/posts/article/:id` and acts accordingly is as follows:
```javascript
  article: {
    get: function(req, res, next) {
      Post.find({_id: req.params.id}).limit(1).exec()
        .then(function(post) {
          res.status(200);
          res.json(post);
        })
        .catch(function(err) {
          return next(err);
        })
      ;
    },
    patch: function(req, res, next) {
      Post.find({_id: req.params.id}).limit(1).exec()
        .then(function(post) {
          if(post.userID !== req.user['_id']) {
            var err = new Error('This post does not belong to you.');
            return next(err);
          }
          var body = req.body;
          body.userID = req.user['_id'];
          body.username = req.user.userName;
          Post.update({_id: {$eq: req.params.id}}, body)
            .then(function(newpost) {
              res.status(200);
              res.json(newpost);
            })
          ;
        })
        .catch(function(err) {
          return next(err);
        })
      ;
    },
    del: function(req, res, next) {
      Post.find({_id: req.params.id}).limit(1).exec()
        .then(function(post) {
          if(post.userID !== req.user['_id']) {
            var err = new Error('This post does not belong to you.');
            return next(err);
          }
          Post.remove({_id: {$eq: req.params.id}})
            .then(function() {
              res.sendStatus(200);
            })
          ;
        })
        .catch(function(err) {
          return next(err);
        })
      ;
    },
  }
```

The error that is returned when executing the get method on an existing article id is as follows:
```javascript
{
  "message": "Not Found",
  "error": "Error: Not Found
      at /Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/app.js:54:13
      at Layer.handle [as handle_request] (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:312:13)
      at /Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:280:7
      at Function.process_params (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:330:12)
      at next (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:271:10)
      at /Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:618:15
      at next (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:256:14)
      at Function.handle (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:176:3)
      at router (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:46:12)
      at Layer.handle [as handle_request] (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:312:13)
      at /Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:280:7
      at Function.process_params (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:330:12)
      at next (/Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:271:10)
      at /Users/teopaolucci/wdi/teopaolucci/projects/the_blag/blag-backend/node_modules/express/lib/router/index.js:618:15"
}
```
EDIT: Added actual line breaks where `\n`s occurred so that it is more readable.

Any help finding out why this is happening and fixing the problem is appreciated. If this is a simple problem, feel free to add a comment as to where I should look to solving this problem. If you need more of my code from my routes, app.js, or the rest of the controller, I can post them in a comment here too.

Thanks,

-Teo

**Comment by gaand** [comment]
Have a look at `findById`.  I think the problem is one of type, `String` versus `ObjectId`.

**Comment by TeoPaolucci** [comment]
`findById` is mongoose, correct? do I need to add `var mongoose = require('mongoose');`?

**Comment by gaand** [comment]
Are you using Mongoose to create the `Post` object?

**Comment by TeoPaolucci** [comment]
Yes.

**Comment by tdyer** [comment]
http://mongoosejs.com/docs/api.html#model_Model.findById

The Post is a mongoose model that you should've defined elsewhere and required in the above mentioned file.

**Comment by TeoPaolucci** [comment]
`var Post = require('../models').model('Post');` is right at the top of my controller. So I don't think if that's the issue.

Also, I just tested
```javascript
/* snip */
get: function(req, res, next) {
      Post.findById(req.params.id).exec()
        .then(function(post) {
          res.status(200);
          res.json(post);
        })
        .catch(function(err) {
          return next(err);
        })
      ;
    },
/* snip */
```
to no avail as well, getting the same error. After reading the stack trace, it doesn't seem like a syntactical error in my controller, rather the route isn't being found at all (possibly explaining why all of the `/posts/article/:id` methods aren't working).

**Comment by TeoPaolucci** [comment]
I'm going to quickly check my spelling of  article everywhere.

**Comment by TeoPaolucci** [comment]
AHA! Found it!
My routes had `router.route('article/:id')` instead of `router.route('/article/:id')`

**Comment by TeoPaolucci** [comment]
Just tested it, Everything is working fine. Thanks for the help.
