### ISSUE TITLE
Promises promises promises

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#57]
We are getting the following lovely error:
```
{"message":"Page.create(...).exec is not a function","error":"TypeError: Page.create(...).exec is not a function\n at pageController.createPage (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/controllers/pageController.js:35:32)\n at Layer.handle [as handle_request] (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/layer.js:95:5)\n at next (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/route.js:131:13)\n at Route.dispatch (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/route.js:112:3)\n at Layer.handle [as handle_request] (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/layer.js:95:5)\n at /Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:277:22\n at Function.process_params (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:330:12)\n at next (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:271:10)\n at Function.handle (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:176:3)\n at router (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:46:12)\n at Layer.handle [as handle_request] (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:312:13)\n at /Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:280:7\n at Function.process_params (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:330:12)\n at next (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:271:10)\n at /Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:618:15"}
```

When we try to create a page.

Here is the controller: 
```javascript
'use strict';

var mongoose = require("../models/index");
var passport = require('passport');
mongoose.Promise = global.Promise;
var Page = mongoose.model("Page");

var pageController = {


  showAllPages : function(req, res) {
    Page.find(function(error, Pages){
      if (error) {
        console.error(error);
      };
      res.json(Pages);
    });
  },

  showOnePage : function(req, res) {
    Page.findById(req.params.id, function(error, Page){
      if (error) {
        console.error(error);
      }
      res.json(Page);
    });
  },

   createPage : function(req, res, next) {
    var pageCreatePromise = Page.create({
                              title: req.body.title,
                              content: req.body.content,
                              url: req.body.url,
                              owner: req.body.owner
                            }).exec();

    pageCreatePromise
    .then(function(page) {
      res.setStatus(201);
      res.json({page: page});
    }).catch(function(error) {
      res.status(500);
      res.send('Invalid Entry. Please Try Creating a Page Again.');
    });
  },

  updatePage : function(req, res, next) {
      var title = req.body.title;
      var content = req.body.content;

      var pageFindPromise = new Promise(
        function(resolve, reject) {
        var selectedPage =  Page.findById(req.params.id, function(error, Page){
        if (error) {
          reject(error);
        }
        resolve(selectedPage);
        });
      });

    var pageUpdatePromise = function(selectedPage) {
      selectedPage.update({
        title: title,
        content: content
      }, function(error, Page){
        if(error) {
          return;
      }
      res.json(Page);
      });
    };

    pageFindPromise.then(
    pageUpdatePromise).catch(function(error) {
      res.send('Invalid Entry. Please Try Updating Your Page Again.');
    });
  },

  deletePage : function(req, res, error) {
    Page.findByIdAndRemove({_id : req.params.id})
    .exec().then(function(){
      res.json({message: "DELTETED"});
    })
    .catch(function(err){
      res.json({error: error});
    });

  }
};

module.exports = pageController;
```

**Comment by raq929** [comment]
(before, we were using `new Promise` to do this, and it was creating the page and then executing the catch function. So... that was weird, and we're trying to refactor to make this more similar to promises we created with Antony yesterday.

**Comment by srhoulam** [comment]
Have you read the error message?

**Comment by srhoulam** [comment]
It was a problem with using `res.setStatus`, which does not exist, rather than `res.status`.
