### ISSUE TITLE
Trouble deploying to Heroku

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/express-group-project#68]
Looks like the .env file is involved and we have the AWS stuff in there and don't want to get blacklisted from Amazon so we would love a little help at lunch!  We have CRUD, now just need to deploy.

**Comment by jcmeyer10** [comment]
Here is the error message LOL

```Opening still-mountain-2459... done
~/Documents/WDI/Midden/packRat-backend2 (master)$ heroku logs
2015-12-06T22:35:07.393127+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-06T22:35:07.394254+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-06T22:35:07.394494+00:00 app[web.1]: npm ERR! packRat-backend@0.0.0 start: `node ./bin/www`
2015-12-06T22:35:07.394656+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-06T22:35:07.394835+00:00 app[web.1]: npm ERR! 
2015-12-06T22:35:07.395006+00:00 app[web.1]: npm ERR! Failed at the packRat-backend@0.0.0 start script 'node ./bin/www'.
2015-12-06T22:35:07.395173+00:00 app[web.1]: npm ERR! This is most likely a problem with the packRat-backend package,
2015-12-06T22:35:07.395398+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-06T22:35:07.395605+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-06T22:35:07.395823+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-06T22:35:07.396015+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-06T22:35:07.396209+00:00 app[web.1]: npm ERR!     npm owner ls packRat-backend
2015-12-06T22:35:07.396436+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-06T22:35:07.399308+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-06T22:35:07.399083+00:00 app[web.1]: 
2015-12-06T22:35:07.399445+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-06T22:35:08.091514+00:00 heroku[web.1]: Process exited with status 1
2015-12-06T22:35:08.105914+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-06T22:35:42.462739+00:00 heroku[api]: Attach MONGOLAB resource by edieshimel@gmail.com
2015-12-06T22:35:42.462739+00:00 heroku[api]: Release v6 created by edieshimel@gmail.com
2015-12-06T22:35:42.610593+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-06T22:35:43.889114+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-06T22:35:46.729989+00:00 app[web.1]: > packRat-backend@0.0.0 start /app
2015-12-06T22:35:46.729978+00:00 app[web.1]: 
2015-12-06T22:35:46.729991+00:00 app[web.1]: > node ./bin/www
2015-12-06T22:35:46.729992+00:00 app[web.1]: 
2015-12-06T22:35:47.738890+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-12-06T22:35:47.739425+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-06T22:35:47.739546+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-06T22:35:47.740483+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-12-06T22:35:47.740684+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-06T22:35:47.740859+00:00 app[web.1]: npm ERR! packRat-backend@0.0.0 start: `node ./bin/www`
2015-12-06T22:35:47.741068+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-06T22:35:47.741230+00:00 app[web.1]: npm ERR! 
2015-12-06T22:35:47.741417+00:00 app[web.1]: npm ERR! Failed at the packRat-backend@0.0.0 start script 'node ./bin/www'.
2015-12-06T22:35:47.725921+00:00 app[web.1]: module.js:339
2015-12-06T22:35:47.725923+00:00 app[web.1]:     throw err;
2015-12-06T22:35:47.725925+00:00 app[web.1]: 
2015-12-06T22:35:47.741991+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-06T22:35:47.741779+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-06T22:35:47.742180+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-06T22:35:47.741610+00:00 app[web.1]: npm ERR! This is most likely a problem with the packRat-backend package,
2015-12-06T22:35:47.725924+00:00 app[web.1]:     ^
2015-12-06T22:35:47.742387+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-06T22:35:47.742602+00:00 app[web.1]: npm ERR!     npm owner ls packRat-backend
2015-12-06T22:35:47.725925+00:00 app[web.1]: Error: Cannot find module './User'
2015-12-06T22:35:47.725927+00:00 app[web.1]:     at Module.require (module.js:366:17)
2015-12-06T22:35:47.725926+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:337:15)
2015-12-06T22:35:47.742798+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-06T22:35:47.725927+00:00 app[web.1]:     at Function.Module._load (module.js:287:25)
2015-12-06T22:35:47.725928+00:00 app[web.1]:     at Object.<anonymous> (/app/models/index.js:9:24)
2015-12-06T22:35:47.746558+00:00 app[web.1]: 
2015-12-06T22:35:47.725928+00:00 app[web.1]:     at require (module.js:385:17)
2015-12-06T22:35:47.725929+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-06T22:35:47.725929+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-06T22:35:47.725930+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-06T22:35:47.725931+00:00 app[web.1]:     at Module.require (module.js:366:17)
2015-12-06T22:35:47.725930+00:00 app[web.1]:     at Function.Module._load (module.js:311:12)
2015-12-06T22:35:47.725932+00:00 app[web.1]:     at Module._compile (module.js:425:26)
2015-12-06T22:35:47.725931+00:00 app[web.1]:     at require (module.js:385:17)
2015-12-06T22:35:47.725931+00:00 app[web.1]:     at Object.<anonymous> (/app/lib/passport.js:11:16)
2015-12-06T22:35:47.725932+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-06T22:35:47.725932+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-12-06T22:35:47.725933+00:00 app[web.1]:     at Function.Module._load (module.js:311:12)
2015-12-06T22:35:47.734404+00:00 app[web.1]: 
2015-12-06T22:35:47.746902+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-06T22:35:47.747125+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-06T22:35:48.487025+00:00 heroku[web.1]: Process exited with status 1
2015-12-06T22:35:48.504043+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-06T22:43:05.909954+00:00 heroku[slug-compiler]: Slug compilation started
2015-12-06T22:43:05.909959+00:00 heroku[slug-compiler]: Slug compilation finished
2015-12-06T22:43:05.763391+00:00 heroku[api]: Deploy b773f00 by edieshimel@gmail.com
2015-12-06T22:43:05.763391+00:00 heroku[api]: Release v7 created by edieshimel@gmail.com
2015-12-06T22:43:06.327955+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-06T22:43:07.464902+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-06T22:43:09.566412+00:00 app[web.1]: 
2015-12-06T22:43:09.566432+00:00 app[web.1]: > packRat-backend@0.0.0 start /app
2015-12-06T22:43:09.566434+00:00 app[web.1]: > node ./bin/www
2015-12-06T22:43:09.566434+00:00 app[web.1]: 
2015-12-06T22:43:10.198765+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-12-06T22:43:10.199230+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-06T22:43:10.200901+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-12-06T22:43:10.199587+00:00 app[web.1]: npm ERR! node v5.0.0
2015-12-06T22:43:10.201445+00:00 app[web.1]: npm ERR! packRat-backend@0.0.0 start: `node ./bin/www`
2015-12-06T22:43:10.201119+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-06T22:43:10.201600+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-06T22:43:10.201775+00:00 app[web.1]: npm ERR! 
2015-12-06T22:43:10.201947+00:00 app[web.1]: npm ERR! Failed at the packRat-backend@0.0.0 start script 'node ./bin/www'.
2015-12-06T22:43:10.202086+00:00 app[web.1]: npm ERR! This is most likely a problem with the packRat-backend package,
2015-12-06T22:43:10.202246+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-06T22:43:10.202567+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-06T22:43:10.202402+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-06T22:43:10.203037+00:00 app[web.1]: npm ERR!     npm owner ls packRat-backend
2015-12-06T22:43:10.202723+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-06T22:43:10.203206+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-06T22:43:10.206156+00:00 app[web.1]: 
2015-12-06T22:43:10.206328+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-06T22:43:10.206424+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-06T22:43:10.817999+00:00 heroku[web.1]: Process exited with status 1
2015-12-06T22:43:10.832405+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-06T22:43:20.056199+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=still-mountain-2459.herokuapp.com request_id=1185c45b-2c67-445a-8a12-521cfd4240a3 fwd="157.130.220.250" dyno= connect= service= status=503 bytes=
~/Documents/WDI/Midden/packRat-backend2 (master)$ heroku config:set SESSION_SECRET='TTzsfjBQsz+JqornNQ/5dw=='
Setting config vars and restarting still-mountain-2459... done
SESSION_SECRET: TTzsfjBQsz+JqornNQ/5dw==```

**Comment by jrhorn424** [comment]
Seems pretty clear: `2015-12-06T22:35:47.725925+00:00 app[web.1]: Error: Cannot find module './User'`

Took me about 45 seconds to read through scanning for the actual error.

**Comment by jcmeyer10** [comment]
Ah, I was thinking it had something to do with the 'failed at .bin www'
part but that makes sense.  Looks like we ran into the capitalization issue
with Heroku if I remember our file names correctly.  Will look at with team
when we get in.

Seems pretty clear: 2015-12-06T22:35:47.725925+00:00 app[web.1]: Error:
Cannot find module './User'

Took me about 45 seconds to read through scanning for the actual error.

—
Reply to this email directly or view it on GitHub
<https://github.com/ga-wdi-boston/express-group-project/issues/68#issuecomment-162447438>
.

**Comment by jrhorn424** [comment]
:+1:

**Comment by eshimel** [comment]
nope...checked that...checked for a few other issues, we can loose the /.users module issue by commented out some db."" stuff, but now get a "trying to open unclosed connection"  We've gone through all of our db.mongoose connection points to try to find an open one...nothing.  any other thoughts on what would be the issue? -es

**Comment by jcmeyer10** [comment]
Set up some time with Antony tomorrow, will close issue when I get home
